### PR TITLE
Hid sony backport 4.9

### PR DESCRIPTION
**Pull request by cdu13a**
Back port of the sony playstation ds3/ds4 drivers from the 4.9 kernel.

I tried to keep it to just the sony driver, required hid transport driver changes, and fixes to anything caused by the transport driver changes.
power_supply changes from 4.1 where left out because they don't really change anything the user would notice and they touch to many other drivers.

### CODE REVIEW

**Comment by adamg88** [comment]
The PS4 controller already works doesn't it?

**Comment by cdu13a** [comment]
The PS4 controllers don't reliably work on the current kernel, and not all features are enabled. You can get some of them to pair, some won't. You occasionally get bluetooth i/o errors when connecting them as well. Which is one of the reasons why I back ported the drivers, I had one controller being unreliable and one not pairing. (also coudn't stand the blinking lights on the PS3 controllers, which this pull request also fixes)

This pull request make all of the revisions of the gen 1 PS4 controllers and most of the various PS3 controllers minus a couple clones work with all features enabled. 

However gen 2 PS4 controllers still require 4.10 kernel and some clones require 4.15 with bluez 5.48. 
I have back ported up to the current mainline to cover those two cases, but that is not included here since I have not finished testing that.

**Comment by adamg88** [comment]
@cdu13a stupid question I guess but are you using these commits in a custom build of CE and if so have you noticed any regressions?

**Comment by cdu13a** [comment]
@adamg88 I've been using these commits in my FunHouse builds for a while. I have also tested them with the latest tagged release of CE where the only change was the inclusion of a kernel built with these commits included.  I've not come across any regressions.

**Pull request merged**
