### PR TITLE
media:usb: add tbs5580 driver

### PR DESCRIPTION
**Pull request by smp79**
This will add support for TBS 5580 USB DVB.

### CODE REVIEW

**Comment by Portisch** [comment]
Sorry, but you will need to make a cherry pick if the source is from another place.
Then fix and adjust the commit to fit in our repo.

We can't just merge cp/paste source code as it's a author or copy right issue.

**Comment by smp79** [comment]
Done.

**Comment by vpeter4** [comment]
There is also question on forum for TBS 5990: any chance for that too?

**Comment by smp79** [comment]
I'll look into it

**Pull request merged**
