### PR TITLE
Update avl6862 Fw, taken from Avalink sdk 2.18.19

### PR DESCRIPTION
**Pull request by moham96**
I only tested DVB-S.

### CODE REVIEW

**Comment by Raybuntu** [comment]
Well that's huge. Was this tested?

**Comment by moham96** [comment]
@Raybuntu I only tested DVBS since I don't use other standards, afl1 should test them and confirm.

**Comment by afl1** [comment]
Do you have any serious reason for upgrading to this version? I have this version and also one older. From my testing current version is the best.

**Comment by moham96** [comment]
@afl1 No, not really. the release notes indicate some improvement but nothing I can understand or test so I thought I push them for further testing, If you feel this update is unnecessary or can break things you can remove this PR.

**Comment by afl1** [comment]
Pls, send me release notes.

**Comment by moham96** [comment]
@afl1 give me your email

**Comment by afl1** [comment]
afl2001@gmail.com

**Pull request merged**
