### PR TITLE
Update meson-ir.c

### PR DESCRIPTION
**Pull request by Petelombardo**
Updated according to this patch...   Needs testing.  No clue if it really works.
https://patchwork.kernel.org/patch/10277541/

### CODE REVIEW

**Comment by Raybuntu** [comment]
Thanks. Looks good. I will test it.

**Comment by Petelombardo** [comment]
Let me know if/how I can help test.  I have a spare S905 box I can test
with.

**Comment by Raybuntu** [comment]
I need to test it first but I don't think IR_DEFAULT_TIMEOUT is defined in 3.14

**Comment by adamg88** [comment]
Closing this PR as IR_DEFAULT_TIMEOUT is not defined in 3.14 and we have improved on the meson-ir code since this time.

**Pull request closed without merging**
